version: 2

jobs:
  build:
    docker:
      - image: nicolov/simple_slam_loop_closure:0.0.2
    steps:
      - checkout
      - run:
          name: download data files
          command: scripts/download_data.sh
      - run:
          name: build
          command: scripts/build.sh
      - run:
          name: run
          command: rm -rf out && mkdir out && ./build/new_college
      - run:
          name: plot confusion matrix
          command: ./scripts/ground_truth_comparison.py
      - run:
          name: plot precision/recall curve
          command: ./scripts/precision_recall.py
      - store_artifacts:
          path: out

workflows:
  version: 2
  build:
    jobs:
      - build
